name: Build
on: [push, pull_request, release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
        submodules: true

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v17
      with:
        name: hs-dear-imgui
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix build
